# Generated by Django 4.2.1 on 2023-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='delivery',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='pick_up',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='truck',
            name='current_location',
            field=models.CharField(max_length=10),
        ),
    ]
