# Generated by Django 5.0.6 on 2024-05-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoapp', '0002_alter_cargo_delivery_alter_cargo_pick_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='delivery',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='pick_up',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='truck',
            name='current_location',
            field=models.CharField(max_length=250),
        ),
    ]
